[package]
name = "lab3-myshell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
rustyline = "9.1.0"
nix = "0.23.1"
libc = "0.2"
lazy_static = "1.4.0"
glob = "0.3.0"